### ISSUE TITLE
Create Entity-Relationship Diagram (ERD) 

### ISSUE THREAD

**Issue by AasemElshahat** [AasemElshahat/cyclistcorner#7]
- [x] Identify the Models: Analyze the models.py files in all apps (e.g., products, users, cart) to identify all the entities.
- [x] Determine Relationships: Identify how models are related (e.g., ForeignKey, ManyToManyField, OneToOneField).
- [x] Create ERD Diagram: Use tools like Lucidchart, Draw.io, or any ERD tool to visualize the models and their relationships.
- [x] Validate with Team: Share the diagram with the team to ensure all relationships are accurately represented.
- [x] Incorporate Feedback: Make adjustments based on feedback from the team.

**Comment by Mohammad-Prog1** [comment]
[ERD_Document.pdf](https://github.com/user-attachments/files/17475423/ERD_Document.pdf)

task completed so please take a look and we are waiting for your rating

**Comment by AasemElshahat** [comment]
Great! But we also need the diagrams as well.. I mean not only in a written form. 
@Mohammad-Prog1
